### ISSUE TITLE
Argyle/UIFontExtensions.swift:39: Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by beqramo** [argyle-systems/argyle-link-react-native#10]
when I'm calling `ArgyleSdk.start();` it throws an error (like above, and in the image).  The package is configured according to the docs.  
I'm using:
```
"@argyleio/argyle-plugin-react-native": "^3.0.3",
"react-native": "0.64.1",
```

![image](https://user-images.githubusercontent.com/40486471/118775432-fbdbf180-b897-11eb-907d-453adab693a6.png)

**Comment by Varnius** [comment]
Hi @beqramo. Could you share the code you are using for initialising Link?

**Comment by beqramo** [comment]
Hi, thanks for your answer, it was my error, I forgot to import initialization in my code, your answer gave me that clue :D, thanks.
