### ISSUE TITLE
Are these gradle implementation still relevant on RN 0.74?

### ISSUE THREAD

**Issue by tsachit** [argyle-systems/argyle-link-react-native#127]
These were the gradle implementation we had on `android/app/build.gradle` till React Native 0.73. I tried to upgrade our project to RN 0.74. The first three implementation were failing to make the build.
```
    implementation "com.squareup.okhttp3:okhttp-bom:4.9.2"
    implementation "com.squareup.okhttp3:okhttp"
    implementation "com.squareup.okhttp3:okhttp-urlconnection"
    implementation 'com.argyle:argyle-link-android:5.2.0'
```

I was trying to back trace on which version these were required but there is no installation docs on github and the documentation website does not have older version setup guide, and the [new guide](https://docs.argyle.com/link/initialization#installing-the-react-native-sdk) does not have above implementation anywhere. My question here is do we still need any of those implementation?

**Comment by MindaugasVarkalys** [comment]
Hello @tsachit ,
You can remove them because Gradle includes all the required dependencies for our SDK automatically.
If that doesn't solve your problem feel free to reopen the issue.
