### ISSUE TITLE
How can I use this in expo managed project?

### ISSUE THREAD

**Issue by kamalpandey** [argyle-systems/argyle-link-react-native#14]
While using in expo managed project with following code

```import React, { useEffect } from "react";
import { StyleSheet, Text, View, TouchableOpacity } from "react-native";
import ArgyleSdk from "@argyleio/argyle-plugin-react-native";

const LINK_KEY = "key_here"; // get your key here: https://console.argyle.com/api-keys

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF",
  },
  welcome: {
    fontSize: 20,
    textAlign: "center",
    margin: 10,
  },
  instructions: {
    textAlign: "center",
    color: "#333333",
    marginBottom: 5,
  },
});

const ArgyleTest = () => {
  const handleConfiguration = async () => {
    // Configure the SDK before hand, once. only call ArgyleSdk.start() when the UI is needed
    ArgyleSdk.loginWith(LINK_KEY, "https://api-sandbox.argyle.io/v1", "");
    ArgyleSdk.onUserCreated((res) => console.log("onUserCreated", res));
    ArgyleSdk.onAccountCreated((res) => console.log("onAccountCreated", res));
    ArgyleSdk.onAccountConnected((res) =>
      console.log("onAccountConnected", res)
    );
    ArgyleSdk.onAccountUpdated((res) => console.log("onAccountUpdated", res));
    ArgyleSdk.onAccountRemoved((res) => console.log("onAccountRemoved", res));
    ArgyleSdk.onAccountError((res) => console.log("onAccountError", res));
    ArgyleSdk.onPayDistributionSuccess((res) =>
      console.log("onPayDistributionSuccess", res)
    );
    ArgyleSdk.onPayDistributionError((res) =>
      console.log("onPayDistributionError", res)
    );
    ArgyleSdk.onError((error) => console.log("onError", error));
    ArgyleSdk.onTokenExpired((res) => console.log("onTokenExpired", res));
    ArgyleSdk.onClose(() => console.log("onClose"));

    ArgyleSdk.linkItems(["uber", "lyft"]); // Can be skipped if all Link items are needed
  };

  useEffect(() => {
    handleConfiguration();
  }, []);

  const startNew = async () => {
    ArgyleSdk.start();
  };

  const startExisting = async () => {
    ArgyleSdk.start();
  };

  return (
    <View style={styles.container}>
      <Text style={styles.welcome}>📱️ Argyle Link SDK️</Text>
      <TouchableOpacity onPress={startNew}>
        <Text style={styles.welcome}>Start new</Text>
      </TouchableOpacity>
      <TouchableOpacity onPress={startExisting}>
        <Text style={styles.welcome}>Start existing</Text>
      </TouchableOpacity>
    </View>
  );
};

export default ArgyleTest;
```

It first gives me 

```
[Unhandled promise rejection: TypeError: null is not an object (evaluating 'ARArgyleSdk.loginWith')]
at node_modules/@argyleio/argyle-plugin-react-native/index.js:50:2 in ArgyleSdk.searchScreenSubtitle
at [native code]:null in callFunctionReturnFlushedQueue
```

But After pressing Start New it gives

`[Unhandled promise rejection: TypeError: null is not an object (evaluating 'ARArgyleSdk.start')]
at node_modules/@argyleio/argyle-plugin-react-native/index.js:54:2 in ArgyleSdk.showCategories
at node_modules/react-native/Libraries/Pressability/Pressability.js:691:17 in _performTransitionSideEffects
at node_modules/react-native/Libraries/Pressability/Pressability.js:628:6 in _receiveSignal
at node_modules/react-native/Libraries/Pressability/Pressability.js:524:8 in responderEventHandlers.onResponderRelease
at [native code]:null in forEach
at [native code]:null in callFunctionReturnFlushedQueue
`

Am i missing something here?

**Comment by Varnius** [comment]
Hi @kamalpandey - our React Native Link SDK is a wrapper around native Android/iOS SDKs, therefore Expo is not supported.
I'd like to suggest using web version of our Link SDK in a web view. You can find more info [here](https://argyle.com/docs/products/argyle-link#configuration). Hope that helps!

**Comment by byCedric** [comment]
Hi, I'm from Expo and just want to help clarify some things 😄 

**React Native SDK**
1. Because Argyle use native dependencies for Android and iOS, using the native SDK won't work in the Expo managed workflow using the "classic" build system through `expo build:android` and `expo build:ios`.
2. [EAS is the new build service for Expo](https://docs.expo.io/build/introduction/) and with that, it works out of the box without requiring an [Expo config plugin](https://docs.expo.io/guides/config-plugins/) 😄 (although it won't work in Expo Go)
3. If you still want the same development experience, you can [create a development client](https://docs.expo.io/clients/introduction/) (through EAS  or locally) and run this library in that custom build.

**Web SDK**
This should work fine in your Expo managed app and in Expo Go, since you only use a JS version. However, you could run into some weird behavior with webviews.

Hope this helps!

**Comment by Varnius** [comment]
@byCedric thanks for a detailed answer. I think it covers the situation well, so I'm closing this issue.
