### ISSUE TITLE
Add support for arm64 simulator

### ISSUE THREAD

**Issue by codebutler** [argyle-systems/argyle-link-react-native#20]
Please add support for arm64 simulators to fix development on M1 macs.

![image](https://user-images.githubusercontent.com/3827/155756225-83e93e3c-e6b7-42b0-a152-cce080368b62.png)

![image](https://user-images.githubusercontent.com/3827/155756158-7d503320-bdfd-4df8-ac37-a68bd8bc1c20.png)

Thanks

**Comment by Varnius** [comment]
@codebutler thanks for the feedback - this is something we are exploring. I assume your current workaround for this is setting `EXCLUDED_ARCHS` to `arm64`, right?

**Comment by dekameron22** [comment]
I have same issue, and setting `EXCLUDED_ARCHS` to `arm64` didn't help.

**Comment by Varnius** [comment]
Yeah, workaround suggested by @codebutler should be the way to go for now.
Meanwhile, we are working on a fix - the plan is to release it sometime mid-April.

**Comment by hkeithk** [comment]
hi @Varnius any update on whether the arm64 support will be released in the near future?

**Comment by Varnius** [comment]
@hkeithk Hi there - we will be releasing this on May 4th.

**Comment by Varnius** [comment]
Fixed with [4.1.0](https://github.com/argyle-systems/argyle-link-react-native/releases/tag/4.1.0)
