### ISSUE TITLE
BundleRelease command fails on version 4.3.1

### ISSUE THREAD

**Issue by hkeithk** [argyle-systems/argyle-link-react-native#28]
Hi, we've been trying to upgrade our SDK version. The new version works in app, but the bundleRelease command fails. The error we see is: Android resource linking failed. 

This seems to be the case going back to 4.1.0. We are unable to use any version after that as we cannot create a new bundle for our users. 

Thanks.

**Comment by Varnius** [comment]
@hkeithk thanks for reporting, we will look into it.

**Comment by hkeithk** [comment]
Hey @Varnius, hope you're doing well. Just want to check in on this issue, let me know if theres any way I can help.

**Comment by hkeithk** [comment]
Its been addressed in 4.5.0! Thanks, will close this issue
