### ISSUE TITLE
ArgyleSdk breaks on Upgrade to Koltin 1.7.0 

### ISSUE THREAD

**Issue by scott-dave** [argyle-systems/argyle-link-react-native#31]
Hi team, 
I am trying to upgrade to Koltin 1.7.0. 1.7.0 now throws error on non exhaustive 'when' clauses. Android studio tells me there is a non exhaustive when clause in the @argyleio/argyle-plugin-react-native plugin on file ArgyleSDKModule.kt, line 109. (node_modules/@argyleio/argyle-plugin-react-native/android/src/main/java/com/reactlibrary/ARArgyleSdkModule.kt)

I tried to create an issue on the argyle-plugin-react-native but could not find it

Koltin Docs:
https://kotlinlang.org/docs/compatibility-guide-17.html#prohibit-computing-constant-values-of-complex-boolean-expressions-in-when-condition-branches-and-conditions-of-loops

**Comment by Varnius** [comment]
@scott-dave thanks for reporting this - this is the right place to create issues for the RN SDK.
We will take a look and will get back to you.

**Comment by Varnius** [comment]
Should be fixed with `4.6.3`

**Comment by scott-dave** [comment]
Awesome thanks so much!
