### ISSUE TITLE
[Android Expo build]: ArgyleSdk breaks on Upgrade to Koltin 1.7.10

### ISSUE THREAD

**Issue by johnny-mcfadden-dailypay** [argyle-systems/argyle-link-react-native#41]
Hi team. 

I see there was a previous issue closed with a similar same problem https://github.com/argyle-systems/argyle-link-react-native/issues/31 (seemingly resolved at the time). Perhaps this is a regression on version: `"@argyleio/argyle-plugin-react-native": "^4.7.4"`. 

I've tried to use a few different patch versions of kotlin >= 1.7.0:

<img width="306" alt="Screenshot 2023-02-14 at 10 19 26" src="https://user-images.githubusercontent.com/93137292/218707038-2004a233-a523-4d70-b13a-31b663875a1e.png">

 but still getting kotlin related android build failures with the following: 

<img width="1100" alt="Screenshot 2023-02-14 at 10 21 12" src="https://user-images.githubusercontent.com/93137292/218707458-e6786970-1afa-4f35-bee0-2621a3595b5e.png">

<img width="1135" alt="Screenshot 2023-02-14 at 10 20 54" src="https://user-images.githubusercontent.com/93137292/218707378-dfeca67e-f3af-404c-a8e5-fab4b0b37133.png">

I had a look at the build.gradle file in the repo and noticed a lower kotlin version:

<img width="858" alt="Screenshot 2023-02-14 at 10 22 44" src="https://user-images.githubusercontent.com/93137292/218707831-f3b4dcc6-633d-440e-b83e-7a18e743f673.png">

Decided to give that a go and the android build was successful 🎉 

<img width="321" alt="Screenshot 2023-02-14 at 10 24 15" src="https://user-images.githubusercontent.com/93137292/218708158-dcaacc4a-36eb-4dec-b5e9-33e9a1726597.png">

However, I'm still running into run time issues when trying to run the successfully built android apk with the lower kotlin version and react native argyle sdk. Using `adb logcat` and trying to start the expo dev client simulator build I'm seeing fatal exceptions: 

<img width="846" alt="Screenshot 2023-02-14 at 15 50 18" src="https://user-images.githubusercontent.com/93137292/218788388-a65ec1ff-1be0-4077-ab86-9969e5ce92a5.png">

+ lots of `requestLayout` failures, which I'm assuming is related to the above fatal kotlin error. 

<img width="842" alt="Screenshot 2023-02-14 at 15 59 14" src="https://user-images.githubusercontent.com/93137292/218790647-1d060e9f-875e-4c80-874b-88438d001a6f.png">

Perhaps a fix for building the argylesdk against kotlin `1.7.10` will resolve the run time issues above 🤞 

Appreciate any help or guidance 🙏

**Comment by Varnius** [comment]
@johnny-mcfadden-dailypay thanks for the report - let us look into it!

**Comment by johnny-mcfadden-dailypay** [comment]
@Varnius 

Looks like Argyle needs 3.2.x where ModuleDSL was introduced - https://github.com/InsertKoinIO/koin/tree/3.2.0/core/koin-core/src/commonMain/kotlin/org/koin/dsl

```
02-16 10:20:01.950  5541  6102 I DailyPay.Frida: Rejecting re-init on previously-failed class java.lang.Class<com.argyle.di.u>: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/koin/dsl/ModuleDSLKt;
02-16 10:20:01.950  5541  6102 I DailyPay.Frida:   at void com.argyle.di.u.<clinit>() (SourceFile:1)
02-16 10:20:01.950  5541  6102 I DailyPay.Frida:   at void com.argyle.Argyle.startSDK(android.content.Context) (SourceFile:33)
```

But expo.modules.devlauncher  needs 3.1.x - https://github.com/InsertKoinIO/koin/tree/3.1.6/core/koin-core/src/commonMain/kotlin/org/koin/dsl

https://github.com/expo/expo/blob/master/packages/expo-dev-launcher/android/build.gradle#L120

```
02-15 23:02:33.385  3683  3683 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/koin/dsl/ModuleKt;
02-15 23:02:33.385  3683  3683 E AndroidRuntime: 	at expo.modules.devlauncher.koin.DevLauncherKoinAppKt.<clinit>(DevLauncherKoinApp.kt:16)
02-15 23:02:33.385  3683  3683 E AndroidRuntime: 	at expo.modules.devlauncher.koin.DevLauncherKoinAppKt.access$getKoinAppFactory$p(DevLauncherKoinApp.kt:1)
02-15 23:02:33.385  3683  3683 E AndroidRuntime: 	at expo.modules.devlauncher.koin.DevLauncherKoinContext.<clinit>(DevLauncherKoinApp.kt:35)
02-15 23:02:33.385  3683  3683 E AndroidRuntime: 	at expo.modules.devlauncher.DevLauncherController$Companion.wasInitialized(DevLauncherController.kt:345)
02-15 23:02:33.385  3683  3683 E AndroidRuntime: 	at expo.modules.devlauncher.rncompatibility.DevLauncherReactNativeHostHandler.getUseDeveloperSupport(DevLauncherReactNativeHostHandler.kt:21)
02-15 23:02:33.385  3683  3683 E AndroidRuntime: 	at expo.modules.ReactNativeHostWrapperBase$getUseDeveloperSupport$1.invoke(ReactNativeHostWrapperBase.kt:77)
02-15 23:02:33.385  3683  3683 E AndroidRuntime: 	at expo.modules.ReactNativeHostWrapperBase$getUseDeveloperSupport$1.invoke(ReactNativeHostWrapperBase.kt:77)
02-15 23:02:33.385  3683  3683 E AndroidRuntime: 	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
02-15 23:02:33.385  3683  3683 E AndroidRuntime: 	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
02-15 23:02:33.385  3683  3683 E AndroidRuntime: 	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
02-15 23:02:33.385  3683  3683 E AndroidRuntime: 	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:168)
02-15 23:02:33.385  3683  3683 E AndroidRuntime: 	at expo.modules.ReactNativeHostWrapperBase.getUseDeveloperSupport(ReactNativeHostWrapperBase.kt:78)
02-15 23:02:33.385  3683  3683 E AndroidRuntime: 	at expo.modules.ReactNativeHostWrapperBase.createReactInstanceManager(ReactNativeHostWrapperBase.kt:25)
02-15 23:02:33.385  3683  3683 E AndroidRuntime: 	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
02-15 23:02:33.385  3683  3683 E AndroidRuntime: 	at com.DailyPay.Friday.MainApplication.onCreate(MainApplication.java:66)
```

Similar issue opened with another package attempting compatibility with `expo-dev-client`:
https://github.com/expo/expo/issues/19842

Looks like the Argyle plugin is not compatible with Expo due to Koin breaking backwards-compatibility.

Is there a older version of the argyle react native sdk we should use (not overly keen on this, as we would love to use the latest and greated 4.x versions), or is this something that needs to be resolved with argyle and expo?

Hope this helps, and really appreciate any help or guidance 👍

**Comment by Varnius** [comment]
Hey. Regarding Kotlin version - we will bump it to `1.7.10` with the Link `4.7.5` to sync it with underlying native Link SDK and hopefully that should help with the first problem you reported.
Regarding Koin version issue - I think that's something that should be resolved on Expo side. Downgrading Link SDK would also likely not help as supported Kotlin version would also be `1.6.x` then so you'd run into the first problem again.

**Comment by johnny-mcfadden-dailypay** [comment]
Thanks @Varnius, we have reached out to expo directly too 🤞

**Comment by Varnius** [comment]
@johnny-mcfadden-dailypay `4.7.5` was released, do tell how it goes.

**Comment by johnny-mcfadden-dailypay** [comment]
Awesome, build with: 

<img width="292" alt="Screenshot 2023-02-16 at 16 32 39" src="https://user-images.githubusercontent.com/93137292/219428631-2d0f6f55-f518-46f1-8a0d-4596121903c5.png">

Worked ✅ 

<img width="404" alt="Screenshot 2023-02-16 at 16 32 11" src="https://user-images.githubusercontent.com/93137292/219428527-8e92bb04-3787-4808-954f-744993b34d4e.png"> 

Just working with expo now to try resolve the `koin` issue between expo dev client and argyle. Thanks @Varnius

**Comment by Varnius** [comment]
@johnny-mcfadden-dailypay glad it worker. Could you close this issue if you are fine by resolution? Feel free to open another one in case any new problems arise.
