### ISSUE TITLE
Question: Is there any plans for TypeScript types to ease developer experience? 

### ISSUE THREAD

**Issue by johnny-mcfadden-dailypay** [argyle-systems/argyle-link-react-native#43]

**Comment by Varnius** [comment]
Hey! Yes, we are planning to provide TS typings with upcoming Link 5.

**Comment by Varnius** [comment]
[Link 5](https://github.com/argyle-systems/argyle-link-react-native/releases/tag/5.0.0) is now out, along with typings, so I'm closing this issue. Feel free to re-open in case a problem arises.
